# Generated by Django 3.2.22 on 2023-10-29 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistadatosusuarios',
            fields=[
                ('usuario_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8mb4_general_ci', db_column='Nombre', max_length=100)),
                ('apellido_paterno', models.CharField(db_collation='utf8mb4_general_ci', db_column='Apellido Paterno', max_length=100)),
                ('apellido_materno', models.CharField(db_collation='utf8mb4_general_ci', db_column='Apellido Materno', max_length=100)),
                ('género', models.CharField(db_collation='utf8mb4_general_ci', db_column='Género', max_length=9)),
                ('fecha_de_nacimiento', models.DateField(db_column='Fecha de Nacimiento')),
                ('rol', models.CharField(db_collation='utf8mb4_general_ci', db_column='Rol', max_length=13)),
                ('calle', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Calle', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Ciudad', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Estado', max_length=100, null=True)),
                ('país', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='País', max_length=100, null=True)),
                ('teléfono', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Teléfono', max_length=10, null=True)),
                ('celular', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Celular', max_length=10, null=True)),
                ('correo_electrónico', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Correo Electrónico', max_length=250, null=True)),
                ('rfc', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='RFC', max_length=13, null=True)),
                ('razón_social', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='Razón Social', max_length=50, null=True)),
            ],
            options={
                'db_table': 'VistaDatosUsuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('celular', models.CharField(max_length=10)),
                ('correo_electronico', models.EmailField(max_length=250, null=True)),
                ('url_social', models.URLField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Dato de Contacto',
                'verbose_name_plural': 'Datos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('razon_social', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dato Fiscal',
                'verbose_name_plural': 'Datos Fiscales',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento de Producto',
                'verbose_name_plural': 'Departamentos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_marca', models.CharField(max_length=50)),
                ('descripcion_marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida de Producto',
                'verbose_name_plural': 'Unidades de Medida de Productos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('a', 'transferencia'), ('b', 'efectivo'), ('c', 'tarjeta de credito'), ('d', 'tarjeta de debito')], max_length=1)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vuelto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cajas')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientes')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empleados')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=9, verbose_name='género')),
                ('birth_date', models.DateField()),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('role', models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], max_length=13, verbose_name='rol')),
                ('datos_contacto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datoscontacto')),
                ('datos_fiscales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datosfiscales')),
                ('domicilio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.domicilio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato Personal',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencia_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deparamento_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.departamentoproducto')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datoscontacto')),
                ('datos_fiscales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datosfiscales')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('a', 'abrir'), ('c', 'cerrar')], max_length=1)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cajas')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empleados')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.productos')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
            },
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.domicilio'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
    ]
