# Generated by Django 3.2.22 on 2023-10-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='city',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='domicilio',
            old_name='country',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='domicilio',
            old_name='state',
            new_name='pais',
        ),
    ]
