# Generated by Django 3.2.22 on 2023-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231023_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesusuario',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre completo'),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='role',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], max_length=13, verbose_name='rol'),
        ),
    ]
