# Generated by Django 3.2.22 on 2023-10-24 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('celular', models.CharField(max_length=10)),
                ('correo_electronico', models.EmailField(max_length=250, null=True)),
                ('url_social', models.URLField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Dato de Contacto',
                'verbose_name_plural': 'Datos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('razon_social', models.CharField(max_length=50, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.domicilio')),
            ],
            options={
                'verbose_name': 'Dato Fiscal',
                'verbose_name_plural': 'Datos Fiscales',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento de Producto',
                'verbose_name_plural': 'Departamentos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_marca', models.CharField(max_length=50)),
                ('descripcion_marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida de Producto',
                'verbose_name_plural': 'Unidades de Medida de Productos',
            },
        ),
        migrations.CreateModel(
            name='UsuariosAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=1)),
                ('datos_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datoscontacto')),
            ],
            options={
                'verbose_name': 'Usuario de Acceso',
                'verbose_name_plural': 'Usuarios de Acceso',
            },
        ),
        migrations.RenameModel(
            old_name='DetallesUsuario',
            new_name='DatosPersonales',
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('a', 'transferencia'), ('b', 'efectivo'), ('c', 'tarjeta de credito'), ('d', 'tarjeta de debito')], max_length=1)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vuelto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cajas')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientes')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuariosacceso')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.AddField(
            model_name='usuariosacceso',
            name='datos_personales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datospersonales'),
        ),
        migrations.AddField(
            model_name='usuariosacceso',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencia_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deparamento_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.departamentoproducto')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datoscontacto')),
                ('datos_fiscales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datosfiscales')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('a', 'abrir'), ('c', 'cerrar')], max_length=1)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cajas')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuariosacceso')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.productos')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='datos_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datoscontacto'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='datos_fiscales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datosfiscales'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='datos_personales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datospersonales'),
        ),
    ]
